### ISSUE TITLE
Chapter 2 mentions RCID priority but it is not defined

### ISSUE THREAD

**Issue by pdp7** [riscv-non-isa/riscv-cmqri#6]
Chapter 2 [QoS Identifiers](https://github.com/riscv-non-isa/riscv-cmqri/blob/main/qos_identifiers.adoc#qos-identifiers) mentions:
> To provide differentiated services to workloads, CBQRI defines a mechanism to configure resource usage limits, in the form of capacity or bandwidth, and **optionally a _priority_ for an RCID** in the resource controllers that control accesses to such shared resources.

Priority seems like a odd term to me as I don't think there is anything in the register interface for priority.  I suppose the closest is to a priority is Mweight for unreserved bandwidth.

Maybe it would be better to phrase it as:
> CBQRI defines a mechanism to configure resource usage limits, in the form of capacity or bandwidth, and can allocate part of the resource to a given RCID, in the resource controllers that control accesses to such shared resources.

**Comment by eshiu-rivos** [comment]
Ved,
I assume you meant the access type distinction (code vs. data). Feel free to clarify further.
-Eric

**Comment by ved-rivos** [comment]
It should be reworded as:
"in the form of capacity or bandwidth, per supported access type, for an `RCID` in the resource controllers that control accesses to such shared resources"
